slice_name: Convictions Achieved
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 109__table
  viz_type: big_number_total
  slice_id: 675
  metric:
    aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: case_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: TEXT
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT_DISTINCT(case_id)
    optionName: metric_kv6cotg4x2_odwhkffajz
    sqlExpression: null
  adhoc_filters:
  - expressionType: SIMPLE
    subject: was_the_perpetrator_convicted
    operator: IN
    operatorId: IN
    comparator:
    - 'yes'
    - conviction
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_8ocmhe539do_qm6916jh1ke
  - expressionType: SIMPLE
    subject: date_of_case_reporting
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_eijob1yfap4_g93ifgyprd
  header_font_size: 0.6
  subheader_font_size: 0.15
  y_axis_format: ~g
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 100
query_context: '{"datasource":{"id":109,"type":"table"},"force":false,"queries":[{"filters":[{"col":"was_the_perpetrator_convicted","op":"IN","val":["yes","conviction"]},{"col":"date_of_case_reporting","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"case_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":1,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"TEXT","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(case_id)","optionName":"metric_kv6cotg4x2_odwhkffajz","sqlExpression":null}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"109__table","viz_type":"big_number_total","slice_id":675,"metric":{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"case_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":1,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"TEXT","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(case_id)","optionName":"metric_kv6cotg4x2_odwhkffajz","sqlExpression":null},"adhoc_filters":[{"expressionType":"SIMPLE","subject":"was_the_perpetrator_convicted","operator":"IN","operatorId":"IN","comparator":["yes","conviction"],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_8ocmhe539do_qm6916jh1ke"},{"expressionType":"SIMPLE","subject":"date_of_case_reporting","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":true,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_eijob1yfap4_g93ifgyprd"}],"header_font_size":0.6,"subheader_font_size":0.15,"y_axis_format":"~g","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[100],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 06a885a5-35b1-4912-a753-4f09765b1b91
version: 1.0.0
dataset_uuid: e15357ae-9bd0-4318-8e14-418763354e87
