slice_name: Counties Covered
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 113__table
  viz_type: big_number_total
  slice_id: 664
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: county
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1437
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: TEXT
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT_DISTINCT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT_DISTINCT(county)
    optionName: metric_57i9i1toju9_rdmd64ur8lm
  adhoc_filters:
  - expressionType: SIMPLE
    subject: Date_identified
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_on3wvgfg3t_diqksejjo9h
  header_font_size: 0.6
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 100
query_context: '{"datasource":{"id":113,"type":"table"},"force":false,"queries":[{"filters":[{"col":"Date_identified","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"county","description":null,"expression":null,"filterable":true,"groupby":true,"id":1437,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"TEXT","type_generic":1,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(county)","optionName":"metric_57i9i1toju9_rdmd64ur8lm"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"113__table","viz_type":"big_number_total","slice_id":664,"metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"county","description":null,"expression":null,"filterable":true,"groupby":true,"id":1437,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"TEXT","type_generic":1,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(county)","optionName":"metric_57i9i1toju9_rdmd64ur8lm"},"adhoc_filters":[{"expressionType":"SIMPLE","subject":"Date_identified","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":true,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_on3wvgfg3t_diqksejjo9h"}],"header_font_size":0.6,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[100],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 2fd602e6-ccf9-4fe4-9961-5ff5758c6cdb
version: 1.0.0
dataset_uuid: edf48f2f-5a7b-4078-bb41-d2155d0d256e
