slice_name: Gender Champions Trained
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 113__table
  viz_type: big_number_total
  slice_id: 664
  metric:
    aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: national_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1439
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT_DISTINCT(national_id)
    optionName: metric_57i9i1toju9_rdmd64ur8lm
    sqlExpression: null
  adhoc_filters:
  - expressionType: SIMPLE
    subject: trained
    operator: IN
    operatorId: IN
    comparator:
    - 'YES'
    - 'Yes'
    - 'YES '
    - 'yes'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_i8g8tqnzwbc_ke3dg6rdvbm
  - expressionType: SIMPLE
    subject: Date_identified
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: true
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_on3wvgfg3t_diqksejjo9h
  header_font_size: 0.6
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 100
query_context: '{"datasource":{"id":113,"type":"table"},"force":false,"queries":[{"filters":[{"col":"trained","op":"IN","val":["YES","Yes","YES
  ","yes"]},{"col":"Date_identified","op":"TEMPORAL_RANGE","val":"No filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"national_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":1439,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(national_id)","optionName":"metric_57i9i1toju9_rdmd64ur8lm","sqlExpression":null}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"113__table","viz_type":"big_number_total","slice_id":664,"metric":{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"national_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":1439,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(national_id)","optionName":"metric_57i9i1toju9_rdmd64ur8lm","sqlExpression":null},"adhoc_filters":[{"expressionType":"SIMPLE","subject":"trained","operator":"IN","operatorId":"IN","comparator":["YES","Yes","YES
  ","yes"],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_i8g8tqnzwbc_ke3dg6rdvbm"},{"expressionType":"SIMPLE","subject":"Date_identified","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":true,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_on3wvgfg3t_diqksejjo9h"}],"header_font_size":0.6,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[100],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 954719a2-7948-40f1-8f73-57b78a3d9b38
version: 1.0.0
dataset_uuid: edf48f2f-5a7b-4078-bb41-d2155d0d256e
